name: UI Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone https://github.com/ormi3-2-4/Frontend-Web
        uses: actions/checkout@v2

      - name: Connect to AWS Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          password: ${{ secrets.LIGHTSAIL_PASSWORD }}
          port: 22
          script: |
            # 이동
            cd ${{ secrets.LIGHTSAIL_ROOT_DIR}}/

            #Git Update
            git pull origin main

            #nginx restart
            sudo systemctl restart nginx
      - name: Deployment completed Successfully
        run: echo "Deployment completed successfuly"
